# -------------------------------------------------------------------------------------------
#
#  Welcome to OmegaWarps main configuration file.
#
#  Here you'll find of the settings and options that you can
#  customize to your server needs. Most features are customizable
#  to an extent.
#
#  You can find all the particle effects here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
#  You can find all the sound effects here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
#
# -------------------------------------------------------------------------------------------


# Set the amount of money that the owner of the warp is charged for the warp.
Warp_Cost:
  Enabled: true
  Cost: 5.00

# Set the particle effects that players get when they warp
Warp_Particle_Effects:
  # The particles that happen as the player is warping
  Before_Warp: BUBBLE_POP
  # The particles that happen after the player has warped.
  After_Warp: PORTAL

Sound_Effects:
  # The sound effect that is played as the player warps
  Before_Warp_Sound: ENTITY_ENDERMAN_TELEPORT
  # The sound effect that is played after the player has warped
  After_Warp_Sound: ENTITY_FOX_TELEPORT

# If permissions should be per warp permissions or a single permission for all warps.
# If true, use the permissions `omegawarps.warp.<warpname>` OR `omegawarps.warp.*` for all the warps
# If false, use permission `omegawarps.warps`
Per_Warp_Permissions: true

# If set to true, those with the permission omegawarps.update will receive messages
# when the plugin updates on spigot
Update_Notify: true

# DO NOT EDIT THIS!
Config_Version: 1.1