name: ${project.name}
version: ${project.version}
api-version: ${pl.apiver}
description: ${project.description}
main: ${main.class}

author: ${pl.author}
authors: ${pl.authors}

softdepend:
  - Vault

commands:
  omegawarps:
    description: Main command for the plugin
    aliases: [ow, owarps]
  delwarp:
    description: Command to delete warps
    aliases: [deletewarp, removewarp, destorywarp]
  setwarp:
    description: Command to set warps
    aliases: [createwarp, makewarp, addwarp]
  warp:
    description: Command to use the warps
  checkwarp:
    description: Command to check the warp details
    aliases: [warpinfo, infowarp, warpcheck]
  listwarps:
    description: Command to list all the warps
    aliases: [warpslist, warps]
  clearwarps:
    description: Command to delete all the warps
  omegawarpsdebug:
    description: Command to view debug information
    aliases: [owdebug, warpsdebug, debugwarps]

permissions:
  omegawarps.admin:
    default: false
    description: Grants access to all the commands
    children:
      - omegawarps.reload
      - omegawarps.update
      - omegawarps.setwarp
      - omegawarps.setwarp.others
      - omegawarps.warps
      - omegawarps.delwarp
      - omegawarps.checkwarps
      - omegawarps.listwarps
      - omegawarps.cost.bypass
      - omegawarps.clearwarps
      - omegawarps.debug
      - omegawarps.warps.worldbypass
  omegawarps.reload:
    default: false
    description: Grants access to the reload command
  omegawarps.update:
    default: false
    description: Allows the user to receive the update message in-game
  omegawarps.setwarp:
    default: false
    description: Grants access to the setwarp command
  omegawarps.setwarp.others:
    default: false
    description: Grants access to setting warps for other players
  omegwarps.warps:
    default: false
    description: Grants access to the warp command
  omegawarps.delwarp:
    default: false
    description: Grants access to the delwarp command
  omegawarps.checkwarps:
    default: false
    description: Grants access to the checkwarp command
  omegawarps.listwarps:
    default: false
    description: Grants access to the listwarps command
  omegawarps.cost.bypass:
    default: false
    description: Allows the user to bypass the cost for setting warps
  omegawarps.clearwarps:
    default: false
    description: Grants access to the clearwarps command
  omegawarps.debug:
    default: false
    description: Grants access to the debug command
  omegawarps.warps.worldbypass:
    default: false
    description: Allows the user to bypass the cross world warp block