name: ${project.name}
version: ${project.version}
api-version: 1.15
description: ${project.description}
main: ${main.class}

author: ${pl.author}
authors: ${pl.authors}

softdepend:
  - Vault

Commands:
  - omegawarps
  - delwarp
  - setwarp
  - warp
  - checkwarp
  - listwarps
