blank_issues_enabled: false
contact_links:
  - name: Contact OmegaWeaponDev
    url: https://discord.gg/9nZTPcp
    about: Feel free to join the discord server if you're wanting to speak to OmegaWeaponDev directly instead of submitting an issue!